# Generated by Django 5.2.6 on 2025-09-10 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTemporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField(help_text='Imagen en formato base64')),
                ('letra_detectada', models.CharField(help_text='Letra vocal detectada (A, E, I, O, U)', max_length=1)),
                ('confianza', models.FloatField(help_text='Nivel de confianza de la detección (0.0 - 1.0)')),
                ('coordenadas_mano', models.JSONField(help_text='Coordenadas de los puntos de la mano detectada')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la detección')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si ya fue procesado para entrenamiento')),
            ],
            options={
                'verbose_name': 'Dato Temporal',
                'verbose_name_plural': 'Datos Temporales',
                'db_table': 'bd_temporal',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DatosEntrenados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra_vocal', models.CharField(choices=[('A', 'A'), ('E', 'E'), ('I', 'I'), ('O', 'O'), ('U', 'U')], help_text='Letra vocal validada', max_length=1)),
                ('coordenadas_mano', models.JSONField(help_text='Coordenadas normalizadas de los puntos de la mano')),
                ('caracteristicas', models.JSONField(help_text='Características extraídas para el modelo de ML')),
                ('validado_por_usuario', models.BooleanField(default=False, help_text='Indica si fue validado manualmente')),
                ('timestamp_entrenamiento', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de inclusión en entrenamiento')),
                ('fuente_temporal', models.ForeignKey(blank=True, help_text='Referencia al dato temporal original', null=True, on_delete=django.db.models.deletion.CASCADE, to='vista01.datostemporales')),
            ],
            options={
                'verbose_name': 'Dato Entrenado',
                'verbose_name_plural': 'Datos Entrenados',
                'db_table': 'bd_entrenada',
                'ordering': ['-timestamp_entrenamiento'],
            },
        ),
    ]
