# Generated by Django 5.2.6 on 2025-09-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodel',
            name='feature_stds',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='threshold_method',
            field=models.CharField(default='percentile', max_length=32),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='threshold_param',
            field=models.FloatField(default=0.88),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='thresholds',
            field=models.JSONField(default=dict),
        ),
    ]
