# Generated by Django 5.2.6 on 2025-09-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista02', '0002_trainingmodel_threshold_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodel',
            name='feature_stds',
            field=models.JSONField(default=dict),
        ),
    ]
